menu:
- {name: 'bio', url: '/bio'}
- {name: 'book', url: '/book'}
- {name: 'writing', url: '/writing'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Dylan McNulty-Holmes', email: 'dyl.amh@protonmail.com', image: 'assets/img/dylan_mcnulty_holmes_bio.jpg'}

contacts:
- {name: 'Dylan McNulty-Holmes', email: 'dyl.amh@protonmail.com', image: 'assets/img/dylan_mcnulty_holmes_bio.jpg'}